### ISSUE TITLE
Feedback and Ask about Installation in Current Develop Branch 

### ISSUE THREAD

**Issue by kholisrag** [mattjhayes/nmeta#113]
Because my ubuntu upgrade to 16.04.2
I used the develop branch
I follow the install instruction in develop brach too with small modification, as :
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git git-flow python-pytest python-yaml
#dpkt error
pip install --upgrade pip
pip install ryu dpkt mock requests simplejson eve coloredlogs voluptuous --user --upgrade
#and then install mongodb, also clone this repo and switch to develop branch
cd ~/nmeta/tests/; py.test
# the test is successful. but when running nmeta
ryu-manager ~/nmeta/nmeta/nmeta.py
```
I upgraded to version : 
- pip to 9.0.1
- ryu to 4.13
- dpkt to 1.9.1
- mock to 2.0.0
- requests to 2.9.1
- simplejson to 3.10.0
- Eve to 0.7.4
- coloredlogs to 7.0
- voluptuous to 0.10.5

Console Output :
```
Registered VCS backend: git
Registered VCS backend: hg
Registered VCS backend: svn
Registered VCS backend: bzr
loading app /home/kholisrag/nmeta/nmeta/nmeta.py
Traceback (most recent call last):
  File "/home/kholisrag/.local/lib/python3.5/site-packages/ryu/utils.py", line 87, in import_module
    return importlib.import_module(modname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named '/home/kholisrag/nmeta/nmeta/nmeta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kholisrag/.local/bin/ryu-manager", line 11, in <module>
    sys.exit(main())
  File "/home/kholisrag/.local/lib/python3.5/site-packages/ryu/cmd/manager.py", line 78, in main
    app_mgr.load_apps(app_lists)
  File "/home/kholisrag/.local/lib/python3.5/site-packages/ryu/base/app_manager.py", line 415, in load_apps
    cls = self.load_app(app_cls_name)
  File "/home/kholisrag/.local/lib/python3.5/site-packages/ryu/base/app_manager.py", line 392, in load_app
    mod = utils.import_module(name)
  File "/home/kholisrag/.local/lib/python3.5/site-packages/ryu/utils.py", line 102, in import_module
    mod = importlib.import_module(name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/kholisrag/nmeta/nmeta/nmeta.py", line 45, in <module>
    import config
  File "/home/kholisrag/nmeta/nmeta/config.py", line 141
    except yaml.YAMLError, exception:
                         ^
SyntaxError: invalid syntax
```
when I try remove the ',' in last line, it's running but in the console output there is a event_loop error message in almost every seciond, like this:

```
05:21:42.930 ryu.base.app_manager[27418] _event_loop ERROR NMeta: Exception occurred during handler processing. Backtrace from offending handler [packet_in] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/home/kholisrag/.local/lib/python3.5/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/kholisrag/nmeta/nmeta/nmeta.py", line 166, in packet_in
    datetime.datetime.now())
  File "/home/kholisrag/nmeta/nmeta/flows.py", line 635, in ingest_packet
    pkt.eth_src = _mac_addr(eth.src)
  File "/home/kholisrag/nmeta/nmeta/flows.py", line 981, in _mac_addr
    return ':'.join('%02x' % ord(b) for b in address)
  File "/home/kholisrag/nmeta/nmeta/flows.py", line 981, in <genexpr>
    return ':'.join('%02x' % ord(b) for b in address)
TypeError: ord() expected string of length 1, but int found
```

How to fix it?,
Thanks for the answer

**Comment by mattjhayes** [comment]
I suspect the problem may be the Python version. Can try in version 2.7.x Python?

**Comment by kholisrag** [comment]
@mattjhayes I hava Python2.7 and Python.3.5, how to switch ryu to python2.7 ?
I think it's default when install

**Comment by kholisrag** [comment]
Fixed, Using:
pip2.7 install ryu dpkt mock requests simplejson eve coloredlogs voluptuous --user --upgrade

Thanks
