### ISSUE TITLE
Bugs in Function validate_location

### ISSUE THREAD

**Issue by kholisrag** [mattjhayes/nmeta#114]
Bug in Function validate_location
```
12:55:43 policy[7323] validate DEBUG validating data={'set_desc': 'Except All Rulesets', 'qos_treatment': 'constrained_bw'}
12:55:43 policy[7323] validate DEBUG validating data={'match_type': 'any', 'classifiers_list': [{'location_src': 'internal'}]}
12:55:43 policy[7323] validate DEBUG validating data={'location_src': 'internal'}
Traceback (most recent call last):
  File "/home/kholisrag/.local/bin/ryu-manager", line 11, in <module>
    sys.exit(main())
  File "/home/kholisrag/.local/lib/python2.7/site-packages/ryu/cmd/manager.py", line 81, in main
    services.extend(app_mgr.instantiate_apps(**contexts))
  File "/home/kholisrag/.local/lib/python2.7/site-packages/ryu/base/app_manager.py", line 509, in instantiate_apps
    self._instantiate(app_name, cls, *args, **kwargs)
  File "/home/kholisrag/.local/lib/python2.7/site-packages/ryu/base/app_manager.py", line 495, in _instantiate
    app = cls(*args, **kwargs)
  File "/home/kholisrag/nmeta/nmeta/nmeta.py", line 83, in __init__
    self.policy = policy.Policy(self.config)
  File "/home/kholisrag/nmeta/nmeta/policy.py", line 431, in __init__
    self.tc_rules = TCRules(self)
  File "/home/kholisrag/nmeta/nmeta/policy.py", line 510, in __init__
    self.rules_list.append(TCRule(self, policy, idx))
  File "/home/kholisrag/nmeta/nmeta/policy.py", line 538, in __init__
    policy, condition))
  File "/home/kholisrag/nmeta/nmeta/policy.py", line 658, in __init__
    validate_location(self.logger, policy_value, policy)
  File "/home/kholisrag/nmeta/nmeta/policy.py", line 96, in validate_location
    for policy_location in policy.locations.locations_list:
AttributeError: 'Policy' object has no attribute 'locations'
```
But when I comment the code that related to validate_location, the rule is worked.

**Comment by mattjhayes** [comment]
Thanks for the bug report. I can reproduce by adding a location_src classifier. I will write a fix and also figure out how that got past tests

**Comment by kholisrag** [comment]
cd ~/nmeta/tests/; py.test is also successful

**Comment by mattjhayes** [comment]
I've pushed a fix to develop but haven't had time yet to incorporate better testing for this feature.
